name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.77.1
        override: true
        components: rust-src

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Strip binaries (Linux and macOS)
      if: matrix.os != 'windows-latest'
      run: strip target/release/glowpub

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: glowpub-${{ matrix.os }}
        path: target/release/glowpub

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release Tag
      id: create_tag
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: 'v${{ github.run_number }}',
            message: 'Release v${{ github.run_number }}',
            object: context.sha,
            type: 'commit'
          })

    - name: Push Release Tag
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/glowpub-linux/glowpub
          artifacts/glowpub-windows/glowpub.exe
          artifacts/glowpub-macos/glowpub
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
